# Generated by Django 4.2.5 on 2023-09-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name_plural': 'Musicians'},
        ),
    ]
