# Generated by Django 4.2.5 on 2023-09-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_alter_musician_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='musician_portraits/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician')),
            ],
        ),
    ]
